resolver: nightly-2015-11-03
flags: {}
packages:
- '.'
- '../vr-pal'
- '../glfw-pal'
- '../gl-pal'
- '../oculus-mini'
- '../hydra-hs'
- '../linear-extra'
- '../lens-extra'
- '../halive'
- '../openvr-hs'